#################################################################
# Cluster
#################################################################

cluster.name: lab-es

#################################################################
# Node 
#################################################################

node.name: es01

#################################################################
# Network
#################################################################

network.host: 0.0.0.0

http.port: 9200

#################################################################
# Discovery
#################################################################

discovery.seed_hosts:
  - es01
  - es02
  - es03

cluster.initial_master_nodes:
  - es01
  - es02
  - es03

#################################################################
# Paths
#################################################################

path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch

#################################################################
# Memory
#################################################################

bootstrap.memory_lock: false